name: Build Moja Flint with VCPKG

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        version: 16  # Use Visual Studio 2019

    - name: Install and run Dpendencies
      shell: pwsh
      run: |
         pushd vcpkg
         call vcpkg_setup_vs2022_win_x64.bat
         popd
