name: Build Moja Flint with VCPKG

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        version: 17  # Use Visual Studio 2022

    - name: Install VCPKG if not already installed
      run: |
          git clone https://github.com/microsoft/vcpkg.git FLINT/Source/vcpkg
          pushd FLINT/Source/vcpkg
          .\bootstrap-vcpkg.bat
          popd


    - name: Ensure vcpkg.json is available
      run: |
          copy Source/vcpkg.json FLINT/Source/vcpkg/vcpkg.json

    - name: Build Dependencies with VCPKG
      run: |
        if not exist FLINT/Source/build mkdir FLINT/Source/build
        pushd FLINT/Source/build

        REM If OpenSSL fails to build, just keep retrying until it does.
        cmake -S ../vcpkg ^
          -G "Visual Studio 17 2022" ^
          -DCMAKE_INSTALL_PREFIX=bin ^
          -DVCPKG_TARGET_TRIPLET=moja-x64-windows ^
          -DVCPKG_INSTALL_OPTIONS="--x-abi-tools-use-exact-versions" ^
          -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ^
          -DENABLE_TESTS:BOOL=ON ^
          -DENABLE_MOJA_MODULES_ZIPPER:BOOL=ON ^
          -DENABLE_MOJA_MODULES_GDAL:BOOL=ON ^
          -DENABLE_MOJA_MODULES_LIBPQ:BOOL=ON ^
          -DENABLE_MOJA_MODULES_POCO:BOOL=ON

        popd

    - name: Build Moja Flint Application
      run: |
        mkdir FLINT/Source/flint_build
        cd FLINT/Source/flint_build
        cmake -G "Visual Studio 17 2022" ^
              -DCMAKE_PREFIX_PATH=../build/bin ^
              ../../FLINT/Source
        cmake --build . --config Release

    - name: Test Moja Flint Application
      run: |
        cd FLINT/Source/flint_build
        ctest --output-on-failure
